Front end dan backend sudah selesai
taufikhdyt01/PickUB pull request #4
Opened 2024-06-17 14:32 UTC by Quivers24

Front end dan backend sudah selesai

2024-06-17 14:33 UTC, Quivers24 commented
front end dan backend profile selesai

2024-06-17 14:40 UTC, Quivers24 commented
Profile Card(Front End & Back End)

2024-06-19 03:25 UTC, taufikhdyt01 requested changes
Tidak ada perubahan

2024-06-19 03:26 UTC, taufikhdyt01 commented
double pr

2024-06-19 03:26 UTC, closed without merging